export const COLORS = ['#8b5cf6', '#10b981', '#3b82f6', '#f59e0b', '#ec4899'];

export const COMMON_MAJORS = [
  'Teknik Informatika',
  'Sistem Informasi',
  'Teknik Komputer',
  'Sains Data',
  'Manajemen',
  'Akuntansi',
  'Ilmu Ekonomi',
  'Ekonomi Pembangunan',
  'Hukum',
  'Kedokteran',
  'Kedokteran Gigi',
  'Farmasi',
  'Keperawatan',
  'Kebidanan',
  'Kesehatan Masyarakat',
  'Gizi',
  'Psikologi',
  'Ilmu Komunikasi',
  'Hubungan Internasional',
  'Sosiologi',
  'Ilmu Politik',
  'Administrasi Bisnis/Negara',
  'Teknik Sipil',
  'Arsitektur',
  'Teknik Mesin',
  'Teknik Elektro',
  'Teknik Industri',
  'Teknik Kimia',
  'Teknik Lingkungan',
  'Teknik Perkapalan',
  'Teknik Geologi',
  'Teknik Geodesi',
  'Matematika',
  'Fisika',
  'Kimia',
  'Biologi',
  'Statistika',
  'Aktuaria',
  'Sastra Inggris',
  'Sastra Indonesia',
  'Sastra Jepang',
  'Sastra Arab',
  'Sastra Perancis',
  'Pendidikan Guru SD (PGSD)',
  'Pendidikan Bahasa Inggris',
  'Pendidikan Matematika',
  'Pendidikan Jasmani',
  'Seni Rupa',
  'Desain Komunikasi Visual (DKV)',
  'Desain Interior',
  'Musik',
  'Film dan Televisi',
  'Kehutanan',
  'Pertanian',
  'Agribisnis',
  'Peternakan',
  'Perikanan',
  'Teknologi Pangan',
  'Manajemen Pendidikan Islam',
  'Okupasi Terapi',
  'Pendidikan Biologi',
  'Pendidikan Kimia',
  'Pendidikan Akuntansi',
].sort();
