export const INDONESIA_UNIVERSITIES = [
    "Institut Pertanian Bogor", "Institut Seni Indonesia Denpasar", "Institut Seni Indonesia Padang Panjang",
    "Institut Seni Indonesia Surakarta", "Institut Seni Indonesia Yogyakarta", "Institut Teknologi Bandung",
    "Institut Teknologi Nasional", "Institut Teknologi Nasional Malang", "Institut Teknologi Sepuluh Nopember",
    "Universitas 17 Agustus 1945 Cirebon", "Universitas 17 Agustus 1945 Semarang", "Universitas 17 Agustus 1945 Surabaya",
    "Universitas Ahmad Dahlan", "Universitas Airlangga", "Universitas Andalas", "Universitas Atma Jaya Yogyakarta",
    "Universitas Bakrie", "Universitas Bangka Belitung", "Universitas Bengkulu", "Universitas Bina Nusantara",
    "Universitas Brawijaya", "Universitas Ciputra", "Universitas Dian Nuswantoro", "Universitas Diponegoro",
    "Universitas Gadjah Mada", "Universitas Gunadarma", "Universitas Hasanuddin", "Universitas Indonesia",
    "Universitas Islam Indonesia", "Universitas Islam Negeri Sunan Ampel Surabaya", "Universitas Jambi",
    "Universitas Jember", "Universitas Katolik Indonesia Atma Jaya", "Universitas Katolik Parahyangan",
    "Universitas Kristen Krida Wacana", "Universitas Kristen Petra", "Universitas Kristen Satya Wacana",
    "Universitas Lampung", "Universitas Malikussaleh", "Universitas Mataram", "Universitas Mercu Buana",
    "Universitas Muhammadiyah Magelang", "Universitas Muhammadiyah Malang", "Universitas Muhammadiyah Surakarta",
    "Universitas Muhammadiyah Yogyakarta", "Universitas Mulawarman", "Universitas Narotama", "Universitas Negeri Jakarta",
    "Universitas Negeri Makassar", "Universitas Negeri Malang", "Universitas Negeri Medan", "Universitas Negeri Padang",
    "Universitas Negeri Semarang", "Universitas Negeri Surabaya", "Universitas Negeri Yogyakarta",
    "Universitas Nusa Cendana", "Universitas Padjadjaran", "Universitas Palangka Raya", "Universitas Pamulang",
    "Universitas Pancasila", "Universitas Pasundan", "Universitas Pattimura", "Universitas Pelita Harapan",
    "Universitas Pendidikan Ganesha", "Universitas Pendidikan Indonesia", "Universitas Pertamina", "Universitas Riau",
    "Universitas Sam Ratulangi", "Universitas Sanata Dharma", "Universitas Sebelas Maret", "Universitas Sriwijaya",
    "Universitas Sultan Ageng Tirtayasa", "Universitas Sumatera Utara", "Universitas Syiah Kuala", "Universitas Tadulako",
    "Universitas Tanjungpura", "Universitas Tarumanagara", "Universitas Telkom", "Universitas Terbuka",
    "Universitas Trunojoyo Madura", "Universitas Udayana", "Universitas Widya Mandala Surabaya",
    "Binus University", "Prasetya Mulya University", "Sampoerna University", "Swiss German University",
    "President University", "Politeknik Negeri Bandung", "Politeknik Negeri Jakarta", "Politeknik Negeri Malang",
    "Politeknik Negeri Semarang", "Politeknik Negeri Sriwijaya", "Politeknik Elektronika Negeri Surabaya",
    "Politeknik Perkapalan Negeri Surabaya", "Sekolah Tinggi Akuntansi Negara", "Sekolah Tinggi Ilmu Statistik"
].sort();
